export const FETCH_VEHICLE_LIST_REQUEST = "FETCH_VEHICLE_LIST_REQUEST";
export const FETCH_VEHICLE_LIST_SUCCESS = "FETCH_VEHICLE_LIST_SUCCESS";
export const FETCH_VEHICLE_LIST_ERROR = "FETCH_VEHICLE_LIST_ERROR";
export const FETCH_VEHICLE_LIST_RESET = "FETCH_VEHICLE_LIST_RESET";
