export const FETCH_INVOICE_LIST = "FETCH_INVOICE_LIST";
export const FETCH_INVOICE_LIST_PAGINATION = "FETCH_INVOICE_LIST_PAGINATION";
export const FETCH_INVOICE = "FETCH_INVOICE";
export const INVOICE_ID = "INVOICE_ID";
export const CAR_ID = "CAR_ID";
export const USER_ID = "USER_ID";