export const FETCH_INVOICE_LIST_REQUEST = "FETCH_INVOICE_LIST_REQUEST";
export const FETCH_INVOICE_LIST_SUCCESS = "FETCH_INVOICE_LIST_SUCCESS";
export const FETCH_INVOICE_LIST_ERROR = "FETCH_INVOICE_LIST_ERROR";
export const FETCH_INVOICE_LIST_RESET = "FETCH_INVOICE_LIST_RESET";
export const FETCH_INVOICE = "FETCH_INVOICE";
export const INVOICE_ID = "INVOICE_ID";
export const CAR_ID = "CAR_ID";
export const USER_ID = "USER_ID";
