export const FETCH_CUSTOMER_LIST_REQUEST = "FETCH_CUSTOMER_LIST_REQUEST";
export const FETCH_CUSTOMER_LIST_SUCCESS = "FETCH_CUSTOMER_LIST_SUCCESS";
export const FETCH_CUSTOMER_LIST_ERROR = "FETCH_CUSTOMER_LIST_ERROR";
export const FETCH_CUSTOMER_LIST_RESET = "FETCH_CUSTOMER_LIST_RESET";
export const CUSTOMER_PROFILE = "CUSTOMER_PROFILE";
export const SERVICE_HISTORY_PAGINATION = "SERVICE_HISTORY_PAGINATION";
export const ADD_NEW_CAR = "ADD_NEW_CAR";
