export const FETCH_CUSTOMER_LIST = "FETCH_CUSTOMER_LIST";
export const CUSTOMER_LIST_PAGINATION = "CUSTOMER_LIST_PAGINATION";
export const CUSTOMER_PROFILE = "CUSTOMER_PROFILE";
export const SERVICE_HISTORY_PAGINATION = "SERVICE_HISTORY_PAGINATION";
export const ADD_NEW_CAR = "ADD_NEW_CAR";
