export const FETCH_VEHICLE_LIST = "FETCH_VEHICLE_LIST";
export const VEHICLE_LIST_PAGINATION = "VEHICLE_LIST_PAGINATION";
export const SEARCH_VEHICLE_MODEL = "SEARCH_VEHICLE_MODEL";
export const VEHICLE_DETAILS = "VEHICLE_DETAILS";
export const VEHICLE_DETAILS_ID = "VEHICLE_DETAILS_ID";
export const CUSTOMER_ID = "CUSTOMER_ID";
