export const FETCH_SALES_REQUEST = "FETCH_SALES_REQUEST";
export const FETCH_SALES_SUCCESS = "FETCH_SALES_SUCCESS";
export const FETCH_SALES_ERROR = "FETCH_SALES_ERROR";
export const FETCH_SALES_RESET = "FETCH_SALES_RESET";
